baseURL = 'https://blog.salomon.cloud/'
title = "Vit Salomon's Thoughts"
locale = 'en-us'
copyright = 'Vit Salomon'
enableGitInfo = true
summaryLength = 70

[pagination]
pagerSize = 10

[params]
author = 'Vit Salomon'
description = ''

[params.social]
x = 'VitSalomon'

[taxonomies]
tag = 'tags'
category = 'categories'

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
noClasses = false
lineNos = false
tabWidth = 4

[caches.images]
dir = ':cacheDir/images'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30
